name: Coverage report

on:
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #   threshold: 80 # optional parameter
